package com.soa.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2019-04-05T08:20:59.937+02:00
 * Generated source version: 3.2.5-jbossorg-1
 */
@WebService(targetNamespace = "http://soap.soa.com/", name = "StudentSOAPService")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentSOAPService {

    @WebMethod
    @RequestWrapper(localName = "getStudentsByFirstName", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.GetStudentsByFirstName")
    @ResponseWrapper(localName = "getStudentsByFirstNameResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.GetStudentsByFirstNameResponse")
    @WebResult(name = "students", targetNamespace = "")
    public com.soa.soap.GetStudentsByFirstNameResponse.Students getStudentsByFirstName(
            @WebParam(name = "firstName", targetNamespace = "")
                    java.lang.String firstName
    );

    @WebMethod
    @RequestWrapper(localName = "getStudentsByEmail", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.GetStudentsByEmail")
    @ResponseWrapper(localName = "getStudentsByEmailResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.GetStudentsByEmailResponse")
    @WebResult(name = "students", targetNamespace = "")
    public com.soa.soap.GetStudentsByEmailResponse.Students getStudentsByEmail(
            @WebParam(name = "email", targetNamespace = "")
                    java.lang.String email
    );

    @WebMethod
    @RequestWrapper(localName = "downloadStudentAvatarAsBase64", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.DownloadStudentAvatarAsBase64")
    @ResponseWrapper(localName = "downloadStudentAvatarAsBase64Response", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.DownloadStudentAvatarAsBase64Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String downloadStudentAvatarAsBase64(
            @WebParam(name = "id", targetNamespace = "")
                    java.lang.Integer id
    ) throws IOException_Exception;

    @WebMethod
    @RequestWrapper(localName = "downloadStudentAvatar", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.DownloadStudentAvatar")
    @ResponseWrapper(localName = "downloadStudentAvatarResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.DownloadStudentAvatarResponse")
    public void downloadStudentAvatar(
            @WebParam(name = "id", targetNamespace = "")
                    java.lang.Integer id,
            @WebParam(name = "filePath", targetNamespace = "")
                    java.lang.String filePath
    ) throws IOException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getStudentById", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.GetStudentById")
    @ResponseWrapper(localName = "getStudentByIdResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.GetStudentByIdResponse")
    @WebResult(name = "student", targetNamespace = "")
    public com.soa.soap.StudentEntity getStudentById(
            @WebParam(name = "id", targetNamespace = "")
                    java.lang.Integer id
    );

    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello(
            @WebParam(name = "name", targetNamespace = "")
                    java.lang.String name
    );

    @WebMethod
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.AddStudentResponse")
    public void addStudent(
            @WebParam(name = "student", targetNamespace = "")
                    com.soa.soap.StudentEntity student
    );

    @WebMethod
    @RequestWrapper(localName = "getAllStudents", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.GetAllStudents")
    @ResponseWrapper(localName = "getAllStudentsResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.GetAllStudentsResponse")
    @WebResult(name = "students", targetNamespace = "")
    public com.soa.soap.GetAllStudentsResponse.Students getAllStudents();

    @WebMethod
    @RequestWrapper(localName = "getStudentsByGender", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.GetStudentsByGender")
    @ResponseWrapper(localName = "getStudentsByGenderResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.GetStudentsByGenderResponse")
    @WebResult(name = "students", targetNamespace = "")
    public com.soa.soap.GetStudentsByGenderResponse.Students getStudentsByGender(
            @WebParam(name = "gender", targetNamespace = "")
                    com.soa.soap.Gender gender
    );

    @WebMethod
    @RequestWrapper(localName = "deleteStudentById", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.DeleteStudentById")
    @ResponseWrapper(localName = "deleteStudentByIdResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.DeleteStudentByIdResponse")
    public void deleteStudentById(
            @WebParam(name = "id", targetNamespace = "")
                    java.lang.Integer id
    );

    @WebMethod
    @RequestWrapper(localName = "updateStudent", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.UpdateStudent")
    @ResponseWrapper(localName = "updateStudentResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.UpdateStudentResponse")
    public void updateStudent(
            @WebParam(name = "id", targetNamespace = "")
                    java.lang.Integer id,
            @WebParam(name = "student", targetNamespace = "")
                    com.soa.soap.StudentEntity student
    );

    @WebMethod
    @RequestWrapper(localName = "deleteAllStudents", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.DeleteAllStudents")
    @ResponseWrapper(localName = "deleteAllStudentsResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.DeleteAllStudentsResponse")
    public void deleteAllStudents();

    @WebMethod
    @RequestWrapper(localName = "getStudentsByLastName", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.GetStudentsByLastName")
    @ResponseWrapper(localName = "getStudentsByLastNameResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.GetStudentsByLastNameResponse")
    @WebResult(name = "students", targetNamespace = "")
    public com.soa.soap.GetStudentsByLastNameResponse.Students getStudentsByLastName(
            @WebParam(name = "lastName", targetNamespace = "")
                    java.lang.String lastName
    );

    @WebMethod
    @RequestWrapper(localName = "uploadBase64ImageToStudent", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.UploadBase64ImageToStudent")
    @ResponseWrapper(localName = "uploadBase64ImageToStudentResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.UploadBase64ImageToStudentResponse")
    public void uploadBase64ImageToStudent(
            @WebParam(name = "id", targetNamespace = "")
                    java.lang.Integer id,
            @WebParam(name = "filePath", targetNamespace = "")
                    java.lang.String filePath
    ) throws IOException_Exception;
}
